[package]
name = "calculator"
version = "0.1.0"
authors = ["admin"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.4"
egui_glium = "0.4"
serde="1"